<?php
/**
 * @file
 * Payment Gateway 2co.
 */

/**
 * Constants.
 */
define("PG_2CO_ACTION_URL_SINGLE", 'https://www.2checkout.com/checkout/purchase');
define("PG_2CO_ACTION_URL_MULTI", 'https://www.2checkout.com/checkout/purchase');

/**
 * Implements hook_menu().
 */
function pg_2co_menu() {
  $items = array();

  $items['2co/done'] = array(
    'title' => 'Internal Data',
    'page callback' => 'pg_2co_done_payment',
    'access callback' => TRUE,
    'file' => 'pg_2co.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/pgapi/gateway_settings/2co'] = array(
    'title' => '2co',
    'description' => '2co payment settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pg_2co_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer pgapi'),
    'file' => 'pg_2co.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_pgapi_gw().
 */
function pg_2co_pgapi_gw($op, $a3 = NULL) {
  switch ($op) {
    case 'display name':
      $ret = t('2co Payment Gateway');
      break;

    case 'payment gateway info':
      $ret['name'] = t('2co');
      $prices[variable_get('pg_2co_currency_code', 'USD')] = round(($a3 * variable_get('pg_2co_rate', '1.00')), 2);
      $ret['price'] = $prices;
      break;

    case 'ajax_form':
      $t = $a3;
      return array(
        'element' => pg_2co_get_markup($t),
        'submit' => 'pg_2co_submit',
      );
  }

  return $ret;
}

/**
 * Implements hook_pgapi_transaction().
 */
function pg_2co_pgapi_transaction($status, $t) {
  switch ($status) {
    case PG_PENDING:
      $t->extra['amount'] = round(($t->amount * variable_get('pg_2co_rate', '1.00')), 2);
      break;
  }
}

function pg_2co_get_markup($t) {
  $form['message'] = array(
    '#type' => 'markup',
    '#value' => t('We will charge !amount from your CC', array(
      '!amount' => round(($t->amount * variable_get('pg_2co_rate', '1.00')), 2),
    )),
  );

  return $form;
}

function pg_2co_submit($form, $form_state) {
  $form = drupal_build_form('pg_2co_payform', $form_state);
  $output = drupal_render($form);

  echo '<html><body>' . $output . '<script>pgpayform.submit();</script></body>';
  drupal_exit();
}

function pg_2co_payform($form, &$form_state) {
  $values = $form_state['values'];
  $t = pgapi_transaction_load($values['txnid']);

  $form['sid'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_sid', ''),
  );

  $form['mode'] = array(
    '#type' => 'hidden',
    '#default_value' => '2CO',
  );

  $amount = number_format($t->amount * variable_get('pg_2co_rate', '1.00'), 2);
  $form['li_0_price'] = array(
    '#type' => 'hidden',
    '#default_value' => $amount,
  );

  $form['merchant_order_id'] = array(
    '#type' => 'hidden',
    '#default_value' => $t->txnid,
  );

  $form['demo'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_demo', TRUE),
  );

  $form['lang'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_language', 'en'),
  );

  $form['x_receipt_link_url'] = array(
    '#type' => 'hidden',
    // @fixme
    '#default_value' => url('2co/done', array('absolute' => TRUE)),
  );

  $form['#attributes'] = array('name' => 'pgpayform');
  $form['#action'] = variable_get('pg_2co_action_url', PG_2CO_ACTION_URL_SINGLE);

  return $form;
}
