<?php
/**
 * @file
 * Example PGAPI module.
 */

/**
 * Implements hook_menu().
 */
function pg_example_menu() {
  $items = array();
  $items['pg/example/payment'] = array(
    'title' => 'Example payment',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pg_example_payment'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_FORMID().
 */
function pg_example_payment($form, &$form_state) {
  global $user;

  // Create new transaction every page reload.
  $transaction = new stdClass();
  $transaction->amount = 1;
  $transaction->type = t('billing');
  $transaction->title = t('test');
  $transaction->email = $user->mail;
  pgapi_transaction_save($transaction);

  // Form get transaction info.
  $form += pgapi_payment($form, $form_state, $transaction);
  $form['#submit'] = array('pgapi_payment_submit');

  return $form;
}
