<?php

/**
 * Implementation of hook_perm()
 */

function pg_showtransactions_permission() {
  return array(
    'administer pg_showtransaction' => array(
      'title' => t('Administer pg_showtransaction'),
      'description' => t('Allow to see admin/reports/pg_showtransaction page'),
      'restrict access' => TRUE,
    ),
    'show personal transaction' => array(
      'title' => t('Send money'),
      'description' => t('User can send money to another user'),
      'restrict access' => TRUE,
    ),
  );
}


/**
 * Implementation of hook_menu()
 */

function pg_showtransactions_menu() {


  $items['admin/reports/pg_showtransaction'] = array(
      'title'            => 'PGAPI Transactions',
      'page callback'    => 'pg_showtransactions_history',
      'access callback'  => 'user_access',
      'access arguments' => array('administer pg_showtransaction'),
      'weight'           => 1,
      'file'             => 'pg_showtransactions.admin.inc',
      'description'      => 'Transaction information.',

  );

  $items['admin/reports/showtransactions/edit/%txnid'] = array(
      'title'            => 'Edit transaction',
      'description'      => 'All pgapi data is here.',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('pg_showtransactions_edit',4),
      'access callback'  => 'user_access',
      'access arguments' => array('administer pgapi'),
      'file'             => 'pg_showtransactions.admin.inc',
      'type'             => MENU_CALLBACK,
  );

  $items['user/%user/showtransactions'] = array(
      'title'            => 'Show Transactions',
      'description'      => 'There is transaction history.',
      'page callback'    => 'pg_showtransactions_personal_history',
      'access callback'  => 'user_access',
      'access arguments' => array('show personal transaction'),
      'file'             => 'pg_showtransactions.user.inc',
      'type'             => MENU_LOCAL_TASK,
	  'weight'           => 30,
  );
  
  return $items;
}

/**
 * Implements hook_formfilterapi().
 */
 
function pg_showtransactions_formfilterapi($op,$session_name,&$a1 = NULL){
  if($op == 'filters'){
    $filters = array();
    switch($session_name){
      case 'pg_showtransactions_history';
            $filters['id']= array(
              '#type'  => 'textfield',
              '#title' => t('Ttansaction id'),
              '#where' => "pgt.txnid",
            );
            $filters['name']= array(
              '#type'  => 'textfield',
              '#title' => t('Username'),
              '#where' => array('like' => "u.name"),
            );
            $filters['mail']= array(
              '#type'  => 'textfield',
              '#title' => t('Email'),
              '#where' => array('like' => "pgt.email"),
            );

            $filters['price']= array(
              '#type'  => 'textfield',
              '#title' => t('Amount'),
              '#where' => "pgt.amount",
            );

            $filters['title']= array(
              '#type'  => 'textfield',
              '#title' => t('Title'),
              '#where' => array('like' => "pgt.title"),
            );

            $filters['gateway'] = array(
              '#type'  => 'select',
              '#title' => t('Gateway'),
              '#where' => 'pgt.gateway',
              '#options' => pgapi_get_gateway_options(),
            );          

            $filters['status'] = array(
              '#type'  => 'select',
              '#title' => t('Payment status'),
              '#where' => 'pgt.status',
              '#options' => pgapi_build_status(),
            );          

        break;
      case 'pg_account_operator_history';
            
            $filters['name']= array(
              '#type'  => 'textfield',
              '#title' => t('User'),
              '#where' => "u.name",
            );
          
            $filters['price']= array(
              '#type'  => 'textfield',
              '#title' => t('Amount'),
              '#where' => "pgt.amount",
            );
            $filters['action']= array(
              '#type'  => 'select',
              '#title' => t('Payments'),
              '#where' => array('operation' => "pgt.amount"),
              '#options' => array(
                '> 0' => t('received'),
                '< 0' => t('sent'),
              ),
            );
          
            $filters['status'] = array(
              '#type'  => 'select',
              '#title' => t('Payment status'),
              '#where' => 'pgt.status',
              '#options' => pgapi_build_status(),
            );          

        break;
            
    }
    return $filters;
  }
}


/********************************************************************
 * Other Functions
 ********************************************************************/
function pg_showtransactions_filters_by_type(){
  $filters = array();
  $filters['ID']= array('type'  => 'textfield',
                          'title' => t('ID'),
                          'where' => "t.txnid='%s'",
                       );
  $filters['name']= array('type'  => 'textfield',
                          'title' => t('User'),
                          'where' => "u.name='%s'",
                       );

  $filters['email']= array('type'  => 'textfield',
                          'title' => t('Email'),
                          'where' => "t.email='%s'",
                       );

  $filters['price']= array('type'  => 'textfield',
                          'title' => t('Amount'),
                          'where' => "t.amount='%f'",
                       );

  $filters['product']= array('type'  => 'textfield',
                          'title' => t('Title'),
                          'where' => "t.title='%s'",
                       );
  $filters['method']= array('title' => t('Method'),
                          'where' => "t.method = '%s'",
                          'options' => pgapi_build_gateway(),
                       );

  $filters['status'] = array('title' => t('payment status'),
                         'where' => 't.status = %d',
                         'options' => pgapi_build_status(),
                       );
  return $filters;
}
